### ISSUE TITLE
System.ComponentModel.Win32Exception: 'The system cannot find the file specified'

### ISSUE THREAD

**Issue by ninjasource** [SteveSandersonMS/BlazorElectronExperiment.Sample#5]
Hi,

Thanks for this demo. However, when I run your application I get the following error : "The system cannot find the file specified". I can run regular blazor apps.

Here is the log:

[dotnet:11332] out: Launching Electron on port 51613

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.AspNetCore.Blazor.Electron.ElectronProcess.Start(ProcessStartInfo info)
   at Microsoft.AspNetCore.Blazor.Electron.Launcher.StartElectronProcess(Func`1 callback)
   at StandaloneApp.Program.Main(String[] args) in C:\Users\xxxxx\Source\Repos\BlazorElectronExperiment.Sample\StandaloneApp\Program.cs:line 11

**Comment by SteveSandersonMS** [comment]
I expect you didn't run `npm install`. If you get the latest sources, it does `npm install` automatically on build now.
